### ISSUE TITLE
Can't load model for ru.ispras.texterra.core.nlp.annotators.OpenNLPSentenceDetector

### ISSUE THREAD

**Issue by kuk** [ispras/texterra-py#1]
Здравствуйте, хотел бы попробовать Sentence detection, скачал https://at.ispras.ru/owncloud/index.php/s/Jkgrw6iIInwfKFv/download , распаковал, запустил `bin/texterra server start`, установил `pip install texterra`, выполнил

```
import texterra
api = texterra.API(host='http://localhost:8082/texterra/')
list(api.sentence_detection('anc'))
```
Ошибка 

```
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8082/texterra/nlp?targetType=pos-token
```

```
 bin/texterra server start
окт 31, 2018 6:55:34 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [localhost:8082]
окт 31, 2018 6:55:34 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
2018:10:31 18:55:34,965 [INFO ] ru.ispras.texterra.cli.server.rest.TexterraRESTServer - Started Texterra REST server on port 8082.
2018:10:31 18:57:24,110 [ERROR] ru.ispras.texterra.core.rest.LoggingExceptionMapper -
ru.ispras.texterra.core.exceptions.TexterraConfigException: Can't load model for ru.ispras.texterra.core.nlp.annotators.OpenNLPSentenceDetector
        at ru.ispras.texterra.tools.nlp.base.pipelines.graph.sentence.opennlp.PersistentOpenNLPSentenceDetectorProvider$ModelsIO.load(PersistentOpenNLPSentenceDetectorProvider.java:45)
        at ru.ispras.texterra.tools.nlp.base.pipelines.graph.sentence.opennlp.PersistentOpenNLPSentenceDetectorProvider.get(PersistentOpenNLPSentenceDetectorProvider.java:65)
        at ru.ispras.texterra.tools.nlp.pipelines.graph.PipelineNodeCache.getCachedPipelineNode(PipelineNodeCache.java:89)
        at ru.ispras.texterra.tools.nlp.pipelines.graph.GraphPipelineRegistry.getCachedPipelineNode(GraphPipelineRegistry.java:374)
        at ru.ispras.texterra.tools.nlp.pipelines.graph.PipelineBuilder.buildPipelineNode(PipelineBuilder.java:59)
        at ru.ispras.texterra.tools.nlp.pipelines.graph.PipelineBuilder.buildPipelineNode(PipelineBuilder.java:49)
        at ru.ispras.texterra.tools.nlp.pipelines.graph.PipelineBuilder.buildDependencies(PipelineBuilder.java:81)
        at ru.ispras.texterra.tools.nlp.pipelines.graph.GraphPipeline.traverse(GraphPipeline.java:37)
        at ru.ispras.texterra.api.embedded.nlp.EmbeddedTexterraNLP.lambda$null$1(EmbeddedTexterraNLP.java:53)
        at ru.ispras.texterra.api.embedded.nlp.EmbeddedTexterraNLP$$Lambda$43/143180158.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
        at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474)
        at ru.ispras.texterra.api.embedded.nlp.EmbeddedTexterraNLP.lambda$getPipeline$3(EmbeddedTexterraNLP.java:54)
        at ru.ispras.texterra.api.embedded.nlp.EmbeddedTexterraNLP$$Lambda$37/1246452073.traverse(Unknown Source)
        at ru.ispras.texterra.core.nlp.pipelines.IPipeline.lambda$traverse$0(IPipeline.java:28)
        at ru.ispras.texterra.core.nlp.pipelines.IPipeline$$Lambda$38/1485447047.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
        at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at ru.ispras.texterra.core.nlp.pipelines.IPipeline.traverse(IPipeline.java:29)
        at ru.ispras.texterra.api.embedded.nlp.EmbeddedTexterraNLP.traverse(EmbeddedTexterraNLP.java:40)
        at ru.ispras.texterra.core.rest.nlp.NLPResource.nlpBatch(NLPResource.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Resource not found: models/english/sentdetect/sent.bin
        at ru.ispras.modis.utils.ClasspathUtils.getResourceAsStream(Unknown Source)
        at ru.ispras.modis.utils.ClasspathUtils.getResourceAsStream(Unknown Source)
        at ru.ispras.texterra.tools.nlp.base.pipelines.graph.sentence.opennlp.PersistentOpenNLPSentenceDetectorProvider$ModelsIO.load(PersistentOpenNLPSentenceDetectorProvider.java:41)
        ... 71 more
окт 31, 2018 6:57:24 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: Parameter 4 of type java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>> from public ru.ispras.texterra.core.nlp.datamodel.INLPDocument ru.ispras.texterra.core.rest.nlp.NLPResource.pipeline(ru.ispras.texterra.tools.nlp.ITexterraNLP$PipelineSpecification,java.lang.String,ru.ispras.texterra.core.nlp.utils.NLPDocumentFilteringUtils$FilteringOptions,java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>>) is not resolvable to a concrete type.
WARNING: Parameter 3 of type java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>> from public java.util.List<? extends ru.ispras.texterra.core.nlp.datamodel.INLPDocument> ru.ispras.texterra.core.rest.nlp.NLPResource.nlpBatch(ru.ispras.texterra.core.nlp.datamodel.INLPDocument[],javax.ws.rs.core.UriInfo,java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>>,java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>>) is not resolvable to a concrete type.
WARNING: Parameter 4 of type java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>> from public java.util.List<? extends ru.ispras.texterra.core.nlp.datamodel.INLPDocument> ru.ispras.texterra.core.rest.nlp.NLPResource.nlpBatch(ru.ispras.texterra.core.nlp.datamodel.INLPDocument[],javax.ws.rs.core.UriInfo,java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>>,java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>>) is not resolvable to a concrete type.
WARNING: Return type, java.util.List<? extends ru.ispras.texterra.core.nlp.datamodel.INLPDocument>, of method, public java.util.List<? extends ru.ispras.texterra.core.nlp.datamodel.INLPDocument> ru.ispras.texterra.core.rest.nlp.NLPResource.nlpBatch(ru.ispras.texterra.core.nlp.datamodel.INLPDocument[],javax.ws.rs.core.UriInfo,java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>>,java.util.List<java.lang.Class<? extends ru.ispras.texterra.core.nlp.datamodel.IAnnotation>>), is not resolvable to a concrete type.

```

Не могли бы подсказать, что попробовать, как поправить?

**Comment by alexlag** [comment]
Пакет сервера, скачиваемый по этой ссылке, по большей части поддерживает только русский язык:
```
Определение языка (русский, английский языки)
Разбиение на предложения (только русский язык)
Разметка частей речи (только русский язык)
Лемматизация (только русский язык)
Синтаксический разбор (только русский язык)
Извлечение именованных сущностей (только русский язык)
```
Соответственно, чтобы попробовать Sentence detection, надо использовать либо русские тексты на запущенном сервере, либо подключаться к on-line api по ключу.

**Comment by kuk** [comment]
Не сообразил для теста передать строку на русском )) Спасибо, мне русский и нужен
